## 00 – Setup & Data Check

This notebook verifies that the environment and raw Amazon dataset are ready for downstream analysis.

It will:
- Load the raw Amazon reviews/products data.
- Run basic sanity checks on shape, columns, dtypes, missing values, and duplicates.
- Normalize column names and clean key numeric fields (prices, discounts, ratings, rating counts).
- Expand multi-valued categories and review information into a tidy, row-level structure.
- Save the processed dataset for use in later notebooks (for example, `01_eda.ipynb`).

In [27]:
import numpy as np
import pandas as pd

RAW_PATH = "../data/raw/amazon.csv"
PROCESSED_PATH = "../data/processed/amazon.csv"

df = pd.read_csv(RAW_PATH)

In [ ]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,₹379,₹919,59%,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,280","₹3,045",25%,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...","₹2,219","₹3,080",28%,3.6,468,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...","₹1,399","₹1,890",26%,4,"8,031",Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,863","₹3,690",22%,4.3,"6,987","Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [29]:
def summarize_df(df: pd.DataFrame, name: str = "df") -> None:
    print(f"\n=== SUMMARY: {name} ===")
    print(f"Shape: {df.shape[0]} rows  d7 {df.shape[1]} columns")
    print("\nColumns:", df.columns.tolist())
    print("\nDtypes:")
    print(df.dtypes)
    print("\nMissing values (top 10):")
    print(df.isnull().sum().sort_values(ascending=False).head(10))
    print("\nDuplicate rows:", df.duplicated().sum())


summarize_df(df, name="raw data")
print("\n=== DESCRIBE (head) ===")
print(df.describe(include="all").T.head(10))

print("\n=== INFO ===")
print(df.info())

=== SHAPE ===
Loaded dataset 1465 rows, 16 collumns

=== COLUMNS ===
['product_id', 'product_name', 'category', 'discounted_price', 'actual_price', 'discount_percentage', 'rating', 'rating_count', 'about_product', 'user_id', 'user_name', 'review_id', 'review_title', 'review_content', 'img_link', 'product_link']

=== DTYPES ===
product_id             object
product_name           object
category               object
discounted_price       object
actual_price           object
discount_percentage    object
rating                 object
rating_count           object
about_product          object
user_id                object
user_name              object
review_id              object
review_title           object
review_content         object
img_link               object
product_link           object
dtype: object

=== NULLS ===
rating_count           2
product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

=== DUPLICATES ===
0

=== DESCRIBE ===
        product_id                                       product_name  \
count         1465                                               1465
unique        1351                                               1337
top     B07JW9H4J1  Fire-Boltt Ninja Call Pro Plus 1.83" Smart Wat...
freq             3                                                  5

                                                 category discounted_price  \
count                                                1465             1465
unique                                                211              550
top     Computers&Accessories|Accessories&Peripherals|...             ₹199
freq                                                  233               53

       actual_price discount_percentage rating rating_count  \
count          1465                1465   1465         1463
unique          449                  92     28         1143
top            ₹999                 50%    4.1        9,378
freq            120                  56    244            9

                                            about_product  \
count                                                1465
unique                                               1293
top     [CHARGE & SYNC FUNCTION]- This cable comes wit...
freq                                                    6

                                                  user_id  \
count                                                1465
unique                                               1194
top     AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...
freq                                                   10

                                                user_name  \
count                                                1465
unique                                               1194
top     $@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...
freq                                                   10

                                                review_id  \
count                                                1465
unique                                               1194
top     R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...
freq                                                   10

                                             review_title  \
count                                                1465
unique                                               1194
top     Worked on iPhone 7 and didn’t work on XR,Good ...
freq                                                   10

                                           review_content  \
count                                                1465
unique                                               1212
top     I am not big on camera usage, personally. I wa...
freq                                                    8

                                                 img_link  \
count                                                1465
unique                                               1412
top     https://m.media-amazon.com/images/I/413sCRKobN...
freq                                                    3

                                             product_link
count                                                1465
unique                                               1465
top     https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
freq                                                    1

### 3. Column name normalization

In [30]:
print("Before column normalization:")
print(df.columns.tolist())

df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_", regex=False)

print("\nAfter column normalization:")
print(df.columns.tolist())

['product_id', 'product_name', 'category', 'discounted_price', 'actual_price', 'discount_percentage', 'rating', 'rating_count', 'about_product', 'user_id', 'user_name', 'review_id', 'review_title', 'review_content', 'img_link', 'product_link']
-- Fix applied
['product_id', 'product_name', 'category', 'discounted_price', 'actual_price', 'discount_percentage', 'rating', 'rating_count', 'about_product', 'user_id', 'user_name', 'review_id', 'review_title', 'review_content', 'img_link', 'product_link']

### 4. Numeric and currency cleaning

In [31]:
def clean_numeric_column(df: pd.DataFrame, col: str, pattern: str = r"[^\d.-]") -> None:
    """Utility to strip non-numeric characters and convert a column to numeric."""
    print(f"\n=== Cleaning {col} ===")
    before = df[[col]].head(3)
    print("Before:")
    print(before)

    df[col] = df[col].astype(str).str.replace(pattern, "", regex=True)
    df[col] = pd.to_numeric(df[col], errors="coerce")

    print("After:")
    print(df[[col]].head(3))


clean_numeric_column(df, "discounted_price")
clean_numeric_column(df, "actual_price")
clean_numeric_column(df, "discount_percentage")

   product_id discounted_price
0  B07JW9H4J1             ₹399
1  B098NS6PVG             ₹199
2  B096MSW6CT             ₹199
FIX APPLIED
   product_id  discounted_price
0  B07JW9H4J1             399.0
1  B098NS6PVG             199.0
2  B096MSW6CT             199.0

In [32]:
# Price cleaning for 'actual_price' is handled by clean_numeric_column above.

==========================================
   product_id actual_price
0  B07JW9H4J1       ₹1,099
1  B098NS6PVG         ₹349
2  B096MSW6CT       ₹1,899
FIX APPLIED
   product_id  actual_price
0  B07JW9H4J1        1099.0
1  B098NS6PVG         349.0
2  B096MSW6CT        1899.0

In [33]:
# Discount cleaning for 'discount_percentage' is handled by clean_numeric_column above.

==========================================
   product_id discount_percentage
0  B07JW9H4J1                 64%
1  B098NS6PVG                 43%
2  B096MSW6CT                 90%
FIX APPLIED
   product_id  discount_percentage
0  B07JW9H4J1                   64
1  B098NS6PVG                   43
2  B096MSW6CT                   90

In [34]:
df

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,64,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,43,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,90,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,53,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,379.0,919.0,59,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,2280.0,3045.0,25,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...",2219.0,3080.0,28,3.6,468,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...",1399.0,1890.0,26,4,"8,031",Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,2863.0,3690.0,22,4.3,"6,987","Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [35]:
# reanalysing the columns
print(df.dtypes)
print()
print('unique rating')
print(df['rating'].unique())
print('unique rating_count')
print(df['rating_count'].unique())

## checking how often wrong value occurs
bad_rating_val = df['rating'].astype(str).str.contains(r'\|')
print(df.loc[bad_rating_val,['product_id','rating']].head(3))

product_id              object
product_name            object
category                object
discounted_price       float64
actual_price           float64
discount_percentage      int64
rating                  object
rating_count            object
about_product           object
user_id                 object
user_name               object
review_id               object
review_title            object
review_content          object
img_link                object
product_link            object
dtype: object

unique rating
['4.2' '4.0' '3.9' '4.1' '4.3' '4.4' '4.5' '3.7' '3.3' '3.6' '3.4' '3.8'
 '3.5' '4.6' '3.2' '5.0' '4.7' '3.0' '2.8' '4' '3.1' '4.8' '2.3' '|' '2'
 '3' '2.6' '2.9']
unique rating_count
['24,269' '43,994' '7,928' ... '468' '8,031' '6,987']
      product_id rating
1279  B08L12N5H1      |

In [36]:
# ====================================================================
# fixing types for columns 'rating' and 'rating_count'
# ====================================================================

df['rating'] = df['rating'].replace('|', np.nan)
df['rating'] = pd.to_numeric(df['rating'])
print('RAW')
print(df[['product_id','rating','rating_count']].head(5))

df['rating_count'] = df['rating_count'].astype(str).str.replace('nan','0',regex=False)
df['rating_count'] = df['rating_count'].astype(str).str.replace(',','',regex=False)
df['rating_count'] = pd.to_numeric(df['rating_count'], downcast='integer')

print()
print('FIX APPLIED')
print(df[['product_id','rating','rating_count']].head(5))

RAW
   product_id  rating rating_count
0  B07JW9H4J1     4.2       24,269
1  B098NS6PVG     4.0       43,994
2  B096MSW6CT     3.9        7,928
3  B08HDJ86NZ     4.2       94,363
4  B08CF3B7N1     4.2       16,905

FIX APPLIED
   product_id  rating  rating_count
0  B07JW9H4J1     4.2         24269
1  B098NS6PVG     4.0         43994
2  B096MSW6CT     3.9          7928
3  B08HDJ86NZ     4.2         94363
4  B08CF3B7N1     4.2         16905

In [37]:
# final types check
print(df.dtypes)

product_id              object
product_name            object
category                object
discounted_price       float64
actual_price           float64
discount_percentage      int64
rating                 float64
rating_count             int32
about_product           object
user_id                 object
user_name               object
review_id               object
review_title            object
review_content          object
img_link                object
product_link            object
dtype: object

## Separating categories

In [38]:

# dirty_spend_mask = df['discount_percentage'].astype(str).str.contains(r'\%')
# df["category_list"] = df["category"].astype(str).str.split("|")
# df_exploded = df.explode("category_list")

df["category"] = df["category"].str.split("|")
df = df.explode("category")
# df_exploded["category"].value_counts().head(10)
# df_exploded.head(10)


cols = ["user_id", "user_name", "review_id", "review_title", "review_content"]

# 1) Turn "{A,B,C}" into ["A","B","C"] in each of the columns
for c in cols:
    df[c] = (df[c]
             .astype("string")
             .str.strip()
             .str.split(",")         # split into list
            )

# 2) Trim whitespace inside items
for c in cols:
    df[c] = df[c].apply(lambda xs: [x.strip() for x in xs] if isinstance(xs, list) else xs)

# 3) (optional but important) check aligned lengths
lens = df[cols].map(len)
bad = df[lens.nunique(axis=1) != 1]
print("Rows with mismatched list lengths:", len(bad))

# 4) Zip aligned lists into list-of-tuples per row
df["__zipped__"] = df[cols].apply(lambda r: list(zip(*r)), axis=1)

# 5) Explode to multiple rows
df = df.explode("__zipped__").dropna(subset=["__zipped__"]).copy()

# 6) Expand tuple into columns
df[cols] = pd.DataFrame(df["__zipped__"].tolist(), index=df.index)

# 7) Cleanup
df = df.drop(columns="__zipped__")

df

Rows with mismatched list lengths: 5611

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,399.0,1099.0,64,4.2,24269,High Compatibility : Compatible With iPhone 12...,AG3D6O4STAQKAY2UVGEUV46KN35Q,Manav,R3HXWT0LRP0NMF,Satisfied,Looks durable Charging is fine tooNo complains,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,399.0,1099.0,64,4.2,24269,High Compatibility : Compatible With iPhone 12...,AHMY5CWJMMK5BJRBBSNLYT3ONILA,Adarsh gupta,R2AJM3LFTLZHFO,Charging is really fast,Charging is really fast,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,399.0,1099.0,64,4.2,24269,High Compatibility : Compatible With iPhone 12...,AHCTC6ULH4XB6YHDY6PCH2R772LQ,Sundeep,R6AQJGUP6P86,Value for money,good product.,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,399.0,1099.0,64,4.2,24269,High Compatibility : Compatible With iPhone 12...,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,S.Sayeed Ahmed,R1KD19VHEDV0OR,Product review,Till now satisfied with the quality.,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,399.0,1099.0,64,4.2,24269,High Compatibility : Compatible With iPhone 12...,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,jaspreet singh,R3C02RMYQMK6FC,Good quality,This is a good product . The charging speed is...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,SandwichMakers,2863.0,3690.0,22,4.3,6987,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...",AHXCDNSXAESERITAFELQABFVNLCA,PARDEEP,R2ZC03S4QXOW4Y,Excellent product✌,It is a nice product,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,SandwichMakers,2863.0,3690.0,22,4.3,6987,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...",AGRZD6CHLCUNOLMMIMIHUCG7PIFA,Anindya Pramanik,R186H8YW34BQD5,A good product for household use,easy to use. The grilling function is also won...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,SandwichMakers,2863.0,3690.0,22,4.3,6987,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...",AFQZVGSOSOJHKFQQMCEI4725QEKQ,Vikas Singh,R10NC3D321N59G,मुझे बिल्कुल भी मजा नहीं आया और वापस कर दिया।,Very good product,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,SandwichMakers,2863.0,3690.0,22,4.3,6987,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...",AEALVGXXIP46OZVXKRUXSDWZJMEA,Harshada Pimple,REKF75G4SOAOX,Best product,This is a pretty powerful sandwich maker,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,SandwichMakers,2863.0,3690.0,22,4.3,6987,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...",AGEFL3AY7YXEFZA4ZJU3LP7K7OJQ,Saw a.,R2G0ZT4JQX322I,Good,for home use. The product looks good,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [39]:
df

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,399.0,1099.0,64,4.2,24269,High Compatibility : Compatible With iPhone 12...,AG3D6O4STAQKAY2UVGEUV46KN35Q,Manav,R3HXWT0LRP0NMF,Satisfied,Looks durable Charging is fine tooNo complains,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,399.0,1099.0,64,4.2,24269,High Compatibility : Compatible With iPhone 12...,AHMY5CWJMMK5BJRBBSNLYT3ONILA,Adarsh gupta,R2AJM3LFTLZHFO,Charging is really fast,Charging is really fast,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,399.0,1099.0,64,4.2,24269,High Compatibility : Compatible With iPhone 12...,AHCTC6ULH4XB6YHDY6PCH2R772LQ,Sundeep,R6AQJGUP6P86,Value for money,good product.,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,399.0,1099.0,64,4.2,24269,High Compatibility : Compatible With iPhone 12...,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,S.Sayeed Ahmed,R1KD19VHEDV0OR,Product review,Till now satisfied with the quality.,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,399.0,1099.0,64,4.2,24269,High Compatibility : Compatible With iPhone 12...,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,jaspreet singh,R3C02RMYQMK6FC,Good quality,This is a good product . The charging speed is...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,SandwichMakers,2863.0,3690.0,22,4.3,6987,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...",AHXCDNSXAESERITAFELQABFVNLCA,PARDEEP,R2ZC03S4QXOW4Y,Excellent product✌,It is a nice product,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,SandwichMakers,2863.0,3690.0,22,4.3,6987,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...",AGRZD6CHLCUNOLMMIMIHUCG7PIFA,Anindya Pramanik,R186H8YW34BQD5,A good product for household use,easy to use. The grilling function is also won...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,SandwichMakers,2863.0,3690.0,22,4.3,6987,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...",AFQZVGSOSOJHKFQQMCEI4725QEKQ,Vikas Singh,R10NC3D321N59G,मुझे बिल्कुल भी मजा नहीं आया और वापस कर दिया।,Very good product,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,SandwichMakers,2863.0,3690.0,22,4.3,6987,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...",AEALVGXXIP46OZVXKRUXSDWZJMEA,Harshada Pimple,REKF75G4SOAOX,Best product,This is a pretty powerful sandwich maker,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,SandwichMakers,2863.0,3690.0,22,4.3,6987,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...",AGEFL3AY7YXEFZA4ZJU3LP7K7OJQ,Saw a.,R2G0ZT4JQX322I,Good,for home use. The product looks good,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

# saving processed data to a new file

In [40]:
df.to_csv('../data/processed/amazon.csv', index=False)